# “ass” inside an innocent word
- assistant
- classic
- compass
- glass
- brass
- massive
- password
- assassin
- assault
- casserole
- passage
- passive
- grassroots
- bassoon
- ambassador

# “cum”
- accumulate
- accumulation
- accumulative
- cumulative
- cumulus
- document
- vacuum
- circumstantial
- circumference
- succumbing
- decumulation

# “cock”
- peacock
- cockatoo
- Hitchcock
- cockney
- cockroach
- cockle
- aftershock
- buttock
- cockade
- cockleshell

# “dick”
- dictionary
- dictionaries
- Dickens
- Dickinson
- verdict
- edict
- predict
- prediction
- addict
- addiction
- contradiction

# “fag”
- flag
- flagship
- deflagrate
- conflagration
- defragment
- fragility
- fragile
- fragmentation

# “tit”
- title
- entitled
- utility
- attitude
- institution
- constitutional
- hospitality
- fortitude
- restitution
- partition
- reputation
- litigation
- gratitude
- multitude

# “piss”
- compass
- dismissal
- mississippi
- impossible
- permissible
- impression
- passion
- piston
- pistachio

# “cunt”
- scunthorpe
- accountant
- accounting
- recount
- counter
- county
- country
- encounter
- discount
- punctual
- undercount

# “clit”
- clitheroe
- explicit
- explicitly
- solicitation
- political
- implicit
- replicate
- replication
- transclitic (linguistics)

# “penis”
- penistone
- peninsula
- peninsular
- penicillin
- happiness
- openism   # philosophical term